version: '3.8'

services:
#####################################################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of PHP version: 8, 8.0, 7, 7.4, 7.3
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "7.4"
        # Optional Node.js version
        NODE_VERSION: "none"
    restart: on-failure
    volumes:
      - "../www:/workspace:cached"
    # environment:
    #   - name=value
    # Overrides default command so things don't shut down after the process ends.
    command: php -S localhost:8080 -t /workspace/new.alpha2omegacssi.com

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    # depends_on:
    #   - db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
#####################################################################
#   db:
#     image: mysql:8.0.27
#     restart: unless-stopped
#     volumes:
#       - a2o-mysql-data:/var/lib/mysql
#       - ../sql:/mysql_files/
#       - ./my_conf:/etc/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: developer
#       MYSQL_DATABASE: alphatoo_a2o_backend
#       MYSQL_USER: alpha
#       MYSQL_PASSWORD: developer
#     # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
#     # (Adding the "ports" property to this file will not forward from a Codespace.)

# volumes:
#   a2o-mysql-data: null

